<?php

function follow_extend_follow_networks_alter(&$networks, $uid = 0) {
  // Add a network.
  $networks[$uid]['imdb'] = array(
    'title' => t('IMDB'),
    'domain' => 'imdb.com',
  );

  $networks[$uid]['drupal'] = array(
    'title' => t('Drupal.org'),
    'domain' => 'drupal.org',
  );

  drupal_add_css(drupal_get_path('module', 'follow_extend') .'/follow_extend.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}
